-- Mesh Pi5 Server — Database Schema
-- SQLite 3 with WAL mode
-- Generated by /vp-crystallize on 2026-05-04

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

-- Soldier nodes tracked by the mesh network
CREATE TABLE IF NOT EXISTS soldiers (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    node_id         INTEGER NOT NULL UNIQUE,        -- uint16 from packet
    name            TEXT DEFAULT NULL,               -- user-assigned name
    latitude        REAL NOT NULL DEFAULT 0.0,       -- float32
    longitude       REAL NOT NULL DEFAULT 0.0,       -- float32
    heading         REAL NOT NULL DEFAULT 0.0,       -- float32 degrees
    heart_rate      INTEGER NOT NULL DEFAULT 0,      -- uint8 bpm
    spo2            INTEGER NOT NULL DEFAULT 0,      -- uint8 percent
    temperature     REAL NOT NULL DEFAULT 0.0,       -- float32 celsius
    humidity        REAL NOT NULL DEFAULT 0.0,       -- float32 percent
    pressure        REAL NOT NULL DEFAULT 0.0,       -- float32 hPa
    battery_voltage REAL NOT NULL DEFAULT 0.0,       -- float32 volts
    status_flags    INTEGER NOT NULL DEFAULT 0,      -- uint16 bitmap
    last_seen       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Position history for path trail
CREATE TABLE IF NOT EXISTS position_history (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    node_id     INTEGER NOT NULL,
    latitude    REAL NOT NULL,
    longitude   REAL NOT NULL,
    heading     REAL NOT NULL DEFAULT 0.0,
    timestamp   INTEGER NOT NULL,                    -- uint32 epoch from packet
    recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (node_id) REFERENCES soldiers(node_id)
);

-- System events log (SOS, alerts, geofence, etc.)
CREATE TABLE IF NOT EXISTS events (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    node_id     INTEGER,                             -- NULL for system events
    event_type  TEXT NOT NULL,                        -- 'SOS', 'GEOFENCE_BREACH', 'LOW_BATTERY', etc.
    severity    TEXT NOT NULL DEFAULT 'INFO',         -- 'INFO', 'WARNING', 'CRITICAL'
    message     TEXT NOT NULL,
    data_json   TEXT,                                -- extra JSON payload
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (node_id) REFERENCES soldiers(node_id)
);

-- Commands sent to nodes via gateway
CREATE TABLE IF NOT EXISTS commands (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    target_node_id  INTEGER,                         -- NULL for broadcast
    command_type    TEXT NOT NULL,                    -- 'CONFIG', 'OTA', 'BROADCAST', etc.
    payload         BLOB,                            -- raw command bytes
    status          TEXT NOT NULL DEFAULT 'PENDING',  -- 'PENDING', 'SENT', 'ACKED', 'FAILED'
    retry_count     INTEGER NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at         DATETIME,
    acked_at        DATETIME,
    FOREIGN KEY (target_node_id) REFERENCES soldiers(node_id)
);

-- Geofence zones (Phase 5)
CREATE TABLE IF NOT EXISTS geofences (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL,
    zone_type   TEXT NOT NULL DEFAULT 'SAFE',         -- 'SAFE', 'DANGER', 'RESTRICTED'
    polygon     TEXT NOT NULL,                         -- GeoJSON polygon coordinates
    is_active   INTEGER NOT NULL DEFAULT 1,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_position_history_node_id ON position_history(node_id);
CREATE INDEX IF NOT EXISTS idx_position_history_timestamp ON position_history(timestamp);
CREATE INDEX IF NOT EXISTS idx_events_node_id ON events(node_id);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at);
CREATE INDEX IF NOT EXISTS idx_commands_status ON commands(status);
